# this is the standard for creating a travis yml
language: cpp
addons:
    apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - gcc-4.9
        - g++-4.9
        - clang-3.5
env:
    - MATRIX_EVAL="CC=clang-3.5 && CXX=clang++-3.5"
    - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
script:
    - $CXX travistest.cpp -o result.out
    - ./result.out

before_install:
    - eval "${MATRIX_EVAL}"
